# Generated by Django 3.2.7 on 2021-10-03 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='descriptions',
        ),
        migrations.RenameField(
            model_name='productscategory',
            old_name='description',
            new_name='descriptions',
        ),
    ]
