# Generated by Django 3.2.6 on 2021-09-22 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210830_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='descriptions',
        ),
    ]
